from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('logout', logout),
	path('installation', Installation.as_view()),
    path('', Login.as_view()),
    path('manager', login_required(Manager.as_view())),
    path('manager/clients/<str:client_type>', login_required(Clients.as_view())),
    path('manager/create_client/<str:client_type>', login_required(CreateClientProfile.as_view())),
    path('manager/client_profile/<int:pk>', login_required(ClientProfileManager.as_view())),
    path('manager/client_profile/change/<int:pk>', login_required(ChangeClientProfileManager.as_view())),
    path('manager/create_client_account/<int:pk>', login_required(CreateClientAccount.as_view())),
    path('manager/items', login_required(Items.as_view())),
    path('manager/items/add_item', login_required(Add_item.as_view())),
    path('manager/items/remove/<int:pk>', login_required(Remove_item.as_view())),
    path('manager/application_methods', login_required(ApplicationMethods.as_view())),
    path('manager/application_methods/add', login_required(ApplicationMethods_add.as_view())),
    path('manager/application_methods/remove/<int:pk>', login_required(ApplicationMethods_remove.as_view())),
    path('manager/materials', login_required(Materials_view.as_view())),
    path('manager/materials/add', login_required(Materials_add.as_view())),
    path('manager/materials/remove/<int:pk>', login_required(Materials_remove.as_view())),
    path('manager/orders/add', login_required(Get_order_url.as_view())),
    path('manager/orders/<str:status>', login_required(Orders.as_view())),
    path('manager/orders/add/<int:pk>', login_required(Orders_add.as_view())),
    path('manager/order/position/remove/<int:order_number>/<int:pk>', login_required(OrderPosition_remove.as_view())),
    path('manager/orders/position/remove/<int:client>/<int:pk>', login_required(Position_remove.as_view())),
    path('manager/orders/edit/<int:pk>', login_required(Orders_edit.as_view())),
    path('manager/change_order/<int:pk>', login_required(Change_order.as_view())),
    path('manager/providers', login_required(Manager_providers.as_view())),
    path('manager/logistic_companies', login_required(Manager_logistic_companies.as_view())),
    path('manager/order/<int:pk>/done', login_required(ManagerOrderDone.as_view())),
    path('manager/design/<int:pk>', login_required(ManagerDesign.as_view())),
    path('manager/design/order/<int:order_pk>/position/<int:position_pk>', login_required(ManagerPositionDesign.as_view())),
    path('production', login_required(Production.as_view())),
    path('production/orders/<str:status>', login_required(Production_orders.as_view())),
    path('production/orders/edit/<int:pk>', login_required(Production_orders_edit.as_view())),
    path('production/orders/add_providers/<int:pk>', login_required(Production_orders_edit.as_view())),
    path('production/orders/edit/add_provider/<int:pk>', login_required(ProductionOrderEdit_change_provider.as_view())),
    path('production/providers', login_required(Providers.as_view())),
    path('production/providers/add', login_required(Providers_add.as_view())),
    path('production/providers/change/<int:pk>', login_required(Providers_change.as_view())),
    path('production/design/<int:pk>', login_required(ProductionDesign.as_view())),
    path('production/design/order/<int:order_pk>/position/<int:position_pk>', login_required(ProductionPositionDesign.as_view())),
    path('production/specifications', login_required(Production_specifications.as_view())),
    path('production/specifications/add', login_required(Production_specifications_add.as_view())),
    path('production/specification/remove/<int:pk>', login_required(Production_specifications_remove.as_view())),
    path('production/specification_info/<int:pk>', login_required(ProductionSecification_info.as_view())),
    path('doc/delete/<int:pk>', login_required(DocDelete.as_view())),
    path('designer', login_required(Designer.as_view())),
    path('designer/orders/<str:status>', login_required(Designer_orders.as_view())),
    path('designer/orders/edit/<int:pk>', login_required(Designer_orders_edit.as_view())),
    path('designer/order/<int:order_pk>/position/<int:position_pk>/design/<int:design_pk>/delete', login_required(Delete_position_design.as_view())),
    path('designer/order/<int:order_pk>/position/<int:position_pk>', login_required(Designer_position_design.as_view())),
    path('designer/specifications', login_required(Designer_specifications.as_view())),
    path('designer/specifications/add', login_required(Designer_specifications_add.as_view())),
    path('designer/specification/remove/<int:pk>', login_required(Designer_specifications_remove.as_view())),
    path('designer/specification_info/<int:pk>', login_required(DesignerSecification_info.as_view())),
    path('designer/technical_requirements', login_required(DesignerTechReqsList.as_view())),
    path('designer/technical_requirements/add', login_required(DesignerTechReqAdd.as_view())),
    path('designer/technical_requirement/<int:pk>', login_required(DesignerShowTReq.as_view())),
    path('designer/technical_requirement/edit/<int:pk>', login_required(DesignerEditTReq.as_view())),
    path('designer/technical_requirement/delete/<int:pk>', login_required(DeleteTReq.as_view())),
    path('designer/files/order/<int:pk>/position/<int:position_pk>', login_required(DesignerFilesForProduction.as_view())),
    path('designer/items', login_required(DesignerItems.as_view())),
    path('designer/clients', login_required(DesignerClients.as_view())),
    path('designer/client/<int:pk>', login_required(DesignerClientData.as_view())),
    path('logist', login_required(Logist.as_view())),
    path('logist/orders/<str:status>', login_required(Logist_orders.as_view())),
    path('logist/orders/edit/<int:pk>', login_required(LogistOrderEdit.as_view())),
    path('logist/orders/edit/change/<int:pk>', login_required(LogistOrderEdit_change.as_view())),
    path('logist/shipping/add', login_required(ShippingCompanies_add.as_view())),
    path('logist/shipping', login_required(ShippingCompanies.as_view())),
    path('logist/shipping/delete/<int:pk>', login_required(ShippingCompanies_delete.as_view())),
    path('logist/order/<int:order_pk>/position/<int:position_pk>/info', login_required(DeliveryInfo.as_view())),
    path('logist/links', login_required(LogistLinks.as_view())),
    path('logist/link/<int:pk>/delete', login_required(LinkDelete.as_view())),
    path('logist/clients', login_required(LogistClients.as_view())),
    path('logist/client/<int:pk>', login_required(LogistClientData.as_view())),
    path('client/doc/delete/<int:pk>', login_required(DeleteClientFile.as_view())),
    path('client', login_required(Client.as_view())),
    path('client/profile/<int:pk>', login_required(ClientSelfProfile.as_view())),
    path('client/profile/change/<int:pk>', login_required(ClientSelfProfileChange.as_view())),
    path('client/orders/<str:status>', login_required(ClientOrders.as_view())),
    path('client/orders/edit/<int:pk>', login_required(ClientOrders_edit.as_view())),
    path('client/order/<int:order_pk>/item/<int:position_pk>', login_required(ClientPositionDesign.as_view())),
    path('client/brand/delete/<int:pk>', login_required(RemoveBrandbook.as_view())),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
